<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_search_Acct</name>
   <tag></tag>
   <elementGuidId>4f9936d2-fdb7-421d-872c-34fcef071666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//div//div//div//div//div//div//div//form//div[1]//button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
